/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pouria.chatman.gui;

import com.pouria.chatman.CMConfig;
import com.pouria.chatman.Chatman;
import com.pouria.chatman.CMMessage;
import com.pouria.chatman.CMHelper;
import com.pouria.chatman.OutgoingMsgHandler;
import com.pouria.chatman.classes.CmdFatalErrorExit;
import com.pouria.chatman.classes.CmdInvokeLater;
import com.pouria.chatman.classes.CmdShowError;
import com.pouria.chatman.classes.HistoryTablePagination;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JTextField;
import javax.swing.event.HyperlinkEvent;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.apache.hc.client5.http.classic.methods.HttpPost;
import org.apache.hc.client5.http.entity.UrlEncodedFormEntity;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClientBuilder;
import org.apache.hc.core5.http.HttpEntity;
import org.apache.hc.core5.http.NameValuePair;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.message.BasicNameValuePair;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

/**
 *
 * @author PouriaP
 * 
 * This file has the main() function and is the entry point of the application
 * 
 */
public class ChatFrame extends javax.swing.JFrame {

    private static ChatFrame instance = null; 
    private Chatman chatman;
    private String defaultTextAreaHtml;
	private StyleSheet cssHideTime;
	private StyleSheet cssShowTime;
	private int conversationPaneCssToggle = 1;
    private HistoryTablePagination historyPagination;
	private String[][][] emoticonsArray;
	private int emojisIndex = -1; //-1 chon bare avval mikhaim bere be 0
	private String username;
	private AdjustmentListener scrollListenerAlwaysDown;
	private String textColor;
	private String labelsTheme;
	private String textAreasTheme;
	private TrayIcon trayIconApp, trayIconNewMessage;
	private CMNotifPopup newMessagePopup;
	private CMTheme currentTheme, peerTheme;
	private CMTheme themeChooserSelectedTheme;
	
	private final String TEXTCOLOR_DARK = "#2b2b2b";
	private final String TEXTCOLOR_LIGHT = "#e0e0e0";

	private final String version = "2.0.12";
	private final String appTitle = "Chatman Rises";
	
	
	
    private ChatFrame(){
        initComponents();
    }
    
    
    public static ChatFrame getInstance(){
        if(instance == null)
            instance = new ChatFrame();
        
        return instance;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuRightClick = new javax.swing.JPopupMenu();
        dialogHistory = new javax.swing.JDialog();
        scrollPaneHistory = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        buttonNextHistoryPage = new javax.swing.JButton();
        buttonPrevHistoryPage = new javax.swing.JButton();
        dialogChooseBg = new javax.swing.JDialog();
        panelChooseBg = new javax.swing.JPanel();
        labelBgPrev = new javax.swing.JLabel();
        labelPopupPrev = new javax.swing.JLabel();
        dropdownBgs = new javax.swing.JComboBox<>();
        buttonSelectBg = new javax.swing.JButton();
        labelThemeName = new javax.swing.JLabel();
        scrollPaneConversation = new javax.swing.JScrollPane();
        textAreaConversation = new javax.swing.JEditorPane();
        scrollPaneInput = new javax.swing.JScrollPane();
        textAreaInput = new javax.swing.JEditorPane();
        tableEmojis = new javax.swing.JTable();
        labelConvoBg = new javax.swing.JLabel();
        labelInputBg = new javax.swing.JLabel();
        labelTableBg = new javax.swing.JLabel();
        labelMouseDetector = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        labelNextEmojiPage = new javax.swing.JLabel();
        labelPrevEmojiPage = new javax.swing.JLabel();
        labelSend = new javax.swing.JLabel();
        labelClear = new javax.swing.JLabel();
        labelStatusLabl = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelStatusIcon = new javax.swing.JLabel();
        labelStatusBackground = new javax.swing.JLabel();
        labelFrameBg = new javax.swing.JLabel();
        menubarMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuShowHistory = new javax.swing.JMenuItem();
        menuChooseTheme = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuRemoteShutdown = new javax.swing.JMenuItem();
        menuAbortRemoteShutdown = new javax.swing.JMenuItem();
        menuAbortLocalShutdown = new javax.swing.JMenuItem();
        menuWakeOnLan = new javax.swing.JMenuItem();
        menuSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        menuRightClick.setBackground(new java.awt.Color(51, 51, 51));
        menuRightClick.setForeground(new java.awt.Color(255, 255, 255));

        dialogHistory.setTitle("تاریخچه");
        dialogHistory.setAlwaysOnTop(true);
        dialogHistory.setIconImage(null);
        dialogHistory.setMinimumSize(new java.awt.Dimension(300, 300));
        dialogHistory.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dialogHistoryComponentShown(evt);
            }
        });
        dialogHistory.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogHistoryWindowClosing(evt);
            }
        });

        tableHistory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تاریخ", "متن"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableHistory.setRowHeight(30);
        tableHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableHistoryMouseReleased(evt);
            }
        });
        scrollPaneHistory.setViewportView(tableHistory);

        buttonNextHistoryPage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonNextHistoryPage.setText("صفحه بعد");
        buttonNextHistoryPage.setEnabled(false);
        buttonNextHistoryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextHistoryPageActionPerformed(evt);
            }
        });

        buttonPrevHistoryPage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonPrevHistoryPage.setText("صفحه قبل");
        buttonPrevHistoryPage.setEnabled(false);
        buttonPrevHistoryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevHistoryPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogHistoryLayout = new javax.swing.GroupLayout(dialogHistory.getContentPane());
        dialogHistory.getContentPane().setLayout(dialogHistoryLayout);
        dialogHistoryLayout.setHorizontalGroup(
            dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogHistoryLayout.createSequentialGroup()
                        .addComponent(buttonPrevHistoryPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNextHistoryPage))
                    .addComponent(scrollPaneHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogHistoryLayout.setVerticalGroup(
            dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNextHistoryPage)
                    .addComponent(buttonPrevHistoryPage))
                .addContainerGap())
        );

        dialogChooseBg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogChooseBg.setTitle("انتخاب پس زمینه");
        dialogChooseBg.setIconImage(null);
        dialogChooseBg.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogChooseBg.setPreferredSize(new java.awt.Dimension(800, 620));
        dialogChooseBg.setSize(new java.awt.Dimension(800, 620));
        dialogChooseBg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogChooseBgWindowClosing(evt);
            }
        });

        labelBgPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBgPrev.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " پس زمنیه ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N
        labelBgPrev.setMaximumSize(new java.awt.Dimension(350, 450));
        labelBgPrev.setMinimumSize(new java.awt.Dimension(350, 450));
        labelBgPrev.setPreferredSize(new java.awt.Dimension(350, 450));

        labelPopupPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPopupPrev.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " اعلان ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        dropdownBgs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdownBgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownBgsActionPerformed(evt);
            }
        });

        buttonSelectBg.setText("انتخاب");
        buttonSelectBg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectBgActionPerformed(evt);
            }
        });

        labelThemeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelThemeName.setForeground(new java.awt.Color(51, 51, 51));
        labelThemeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelThemeName.setText("theme name");
        labelThemeName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "نام", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        javax.swing.GroupLayout panelChooseBgLayout = new javax.swing.GroupLayout(panelChooseBg);
        panelChooseBg.setLayout(panelChooseBgLayout);
        panelChooseBgLayout.setHorizontalGroup(
            panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChooseBgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelBgPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdownBgs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPopupPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelChooseBgLayout.createSequentialGroup()
                        .addComponent(buttonSelectBg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelThemeName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelChooseBgLayout.setVerticalGroup(
            panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChooseBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownBgs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelThemeName))
                .addGap(18, 18, 18)
                .addGroup(panelChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPopupPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBgPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSelectBg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogChooseBgLayout = new javax.swing.GroupLayout(dialogChooseBg.getContentPane());
        dialogChooseBg.getContentPane().setLayout(dialogChooseBgLayout);
        dialogChooseBgLayout.setHorizontalGroup(
            dialogChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChooseBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogChooseBgLayout.setVerticalGroup(
            dialogChooseBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChooseBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chatman Rises");
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(500, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        scrollPaneConversation.setBorder(null);
        scrollPaneConversation.setOpaque(false);
        scrollPaneConversation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scrollPaneConversationMouseEntered(evt);
            }
        });

        textAreaConversation.setEditable(false);
        textAreaConversation.setBorder(null);
        textAreaConversation.setContentType("text/html"); // NOI18N
        textAreaConversation.setAutoscrolls(false);
        textAreaConversation.setOpaque(false);
        textAreaConversation.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                textAreaConversationHyperlinkUpdate(evt);
            }
        });
        textAreaConversation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textAreaConversationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textAreaConversationMouseEntered(evt);
            }
        });
        scrollPaneConversation.setViewportView(textAreaConversation);

        getContentPane().add(scrollPaneConversation);
        scrollPaneConversation.setBounds(25, 34, 440, 190);

        scrollPaneInput.setBorder(null);
        scrollPaneInput.setOpaque(false);

        textAreaInput.setBorder(null);
        textAreaInput.setContentType("text/html"); // NOI18N
        textAreaInput.setCaretColor(new java.awt.Color(255, 255, 255));
        textAreaInput.setOpaque(false);
        textAreaInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textAreaInputMouseReleased(evt);
            }
        });
        textAreaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaInputKeyPressed(evt);
            }
        });
        scrollPaneInput.setViewportView(textAreaInput);

        getContentPane().add(scrollPaneInput);
        scrollPaneInput.setBounds(30, 330, 255, 145);

        tableEmojis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableEmojis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableEmojis.setGridColor(new java.awt.Color(255, 255, 255));
        tableEmojis.setOpaque(false);
        tableEmojis.setRowHeight(30);
        tableEmojis.setRowSelectionAllowed(false);
        tableEmojis.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tableEmojis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableEmojisMouseReleased(evt);
            }
        });
        getContentPane().add(tableEmojis);
        tableEmojis.setBounds(300, 328, 175, 150);

        labelConvoBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-top-dark-normal.png"))); // NOI18N
        getContentPane().add(labelConvoBg);
        labelConvoBg.setBounds(20, 10, 460, 230);

        labelInputBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-bottom-dark-normal.png"))); // NOI18N
        getContentPane().add(labelInputBg);
        labelInputBg.setBounds(20, 310, 280, 180);

        labelTableBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-table-dark-normal.png"))); // NOI18N
        getContentPane().add(labelTableBg);
        labelTableBg.setBounds(292, 317, 200, 170);

        labelMouseDetector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMouseDetectorMouseEntered(evt);
            }
        });
        getContentPane().add(labelMouseDetector);
        labelMouseDetector.setBounds(30, 250, 430, 40);
        getContentPane().add(progressBar);
        progressBar.setBounds(30, 240, 435, 14);

        labelNextEmojiPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNextEmojiPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-next-dark-normal.png"))); // NOI18N
        labelNextEmojiPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNextEmojiPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelNextEmojiPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelNextEmojiPageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNextEmojiPageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelNextEmojiPageMouseReleased(evt);
            }
        });
        getContentPane().add(labelNextEmojiPage);
        labelNextEmojiPage.setBounds(390, 490, 30, 25);

        labelPrevEmojiPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrevEmojiPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-prev-dark-normal.png"))); // NOI18N
        labelPrevEmojiPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPrevEmojiPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPrevEmojiPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPrevEmojiPageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelPrevEmojiPageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelPrevEmojiPageMouseReleased(evt);
            }
        });
        getContentPane().add(labelPrevEmojiPage);
        labelPrevEmojiPage.setBounds(350, 490, 30, 25);

        labelSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-send-dark-normal.png"))); // NOI18N
        labelSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSendMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelSendMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelSendMouseReleased(evt);
            }
        });
        getContentPane().add(labelSend);
        labelSend.setBounds(35, 490, 120, 40);

        labelClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/label-clear-dark-normal.png"))); // NOI18N
        labelClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelClearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelClearMouseReleased(evt);
            }
        });
        getContentPane().add(labelClear);
        labelClear.setBounds(160, 490, 120, 40);

        labelStatusLabl.setBackground(new java.awt.Color(51, 51, 51));
        labelStatusLabl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelStatusLabl.setForeground(new java.awt.Color(51, 51, 51));
        labelStatusLabl.setText(":وضعیت");
        getContentPane().add(labelStatusLabl);
        labelStatusLabl.setBounds(20, 560, 150, 30);

        labelStatus.setBackground(new java.awt.Color(51, 51, 51));
        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(51, 51, 51));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelStatus.setText("ارتباط قطع است");
        getContentPane().add(labelStatus);
        labelStatus.setBounds(170, 560, 300, 30);

        labelStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/disconnected.png"))); // NOI18N
        getContentPane().add(labelStatusIcon);
        labelStatusIcon.setBounds(360, 555, 40, 40);

        labelStatusBackground.setBackground(new java.awt.Color(239, 239, 239));
        labelStatusBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatusBackground.setAlignmentY(0.0F);
        labelStatusBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        labelStatusBackground.setOpaque(true);
        getContentPane().add(labelStatusBackground);
        labelStatusBackground.setBounds(-5, 560, 560, 40);

        labelFrameBg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelFrameBg.setIconTextGap(0);
        labelFrameBg.setMaximumSize(new java.awt.Dimension(500, 600));
        labelFrameBg.setMinimumSize(new java.awt.Dimension(500, 600));
        labelFrameBg.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(labelFrameBg);
        labelFrameBg.setBounds(0, 0, 494, 600);

        menubarMain.setBackground(new java.awt.Color(204, 204, 204));

        menuFile.setText("گزینه ها");
        menuFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuFile.setMargin(new java.awt.Insets(0, 10, 0, 0));
        menuFile.setPreferredSize(new java.awt.Dimension(70, 23));
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuShowHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuShowHistory.setText("نمایش تاریخچه");
        menuShowHistory.setToolTipText("");
        menuShowHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShowHistoryActionPerformed(evt);
            }
        });
        menuFile.add(menuShowHistory);

        menuChooseTheme.setText("انتخاب پوسته");
        menuChooseTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChooseThemeActionPerformed(evt);
            }
        });
        menuFile.add(menuChooseTheme);
        menuFile.add(menuSeparator1);

        menuRemoteShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuRemoteShutdown.setText("خاموش کردن از راه دور");
        menuRemoteShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoteShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuRemoteShutdown);

        menuAbortRemoteShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbortRemoteShutdown.setText("توقف خاموشی آن کامپیوتر");
        menuAbortRemoteShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbortRemoteShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuAbortRemoteShutdown);

        menuAbortLocalShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbortLocalShutdown.setText("توقف خاموشی این کامپیوتر");
        menuAbortLocalShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbortLocalShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuAbortLocalShutdown);

        menuWakeOnLan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuWakeOnLan.setText("بیدار کردن");
        menuWakeOnLan.setEnabled(false);
        menuWakeOnLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWakeOnLanActionPerformed(evt);
            }
        });
        menuFile.add(menuWakeOnLan);
        menuFile.add(menuSeparator2);

        menuAbout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbout.setText("درباره");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuFile.add(menuAbout);

        menuExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuExit.setText("خروج");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menubarMain.add(menuFile);

        setJMenuBar(menubarMain);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		hideWindow();
    }//GEN-LAST:event_formWindowClosing

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        
    }//GEN-LAST:event_menuFileActionPerformed

    private void tableEmojisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmojisMouseReleased

        int row = tableEmojis.getSelectedRow();
        int col = tableEmojis.getSelectedColumn();
         
        //replace the emoticon image with the larger image. we also add the width=50 and height=50 for better display
        String img = (String) tableEmojis.getValueAt(row, col);
		img = img.replaceAll("<html>(.*)emoticons(.*\\.gif')\\s(\\/>)<\\/html>", "$1emoticons_large$2  $3");
        
        
        //true = append
        updateInputText(img, true);
        textAreaInput.requestFocus();
    
    }//GEN-LAST:event_tableEmojisMouseReleased

    private void textAreaConversationHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_textAreaConversationHyperlinkUpdate
        //triggered when we click on a link
        if(evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED){
            try{
                String path = evt.getURL().toString();
                
                //open if it was a file
                if(path.contains("file://")){
                    path = path.substring(7);
                    Desktop.getDesktop().open(new File(path));
                }
                //browse if it was a URL
                else
                    Desktop.getDesktop().browse(evt.getURL().toURI());
                
            }catch(IOException e){
                message(CMHelper.getInstance().getStr("url_open_fail") + e.getMessage());
				CMHelper.getInstance().log("failed to open url: " + e.getMessage());
            }catch(Exception e){
                message(CMHelper.getInstance().getStr("bad_url") + e.getMessage());
				CMHelper.getInstance().log("failed to open url: " + e.getMessage());
			}
        }
		
    }//GEN-LAST:event_textAreaConversationHyperlinkUpdate

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void labelClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMouseReleased
		changeLabelIcon((JLabel)evt.getComponent(), "normal");
		clearInputText();
    }//GEN-LAST:event_labelClearMouseReleased

    private void textAreaInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaInputMouseReleased
        //show the right-click menu
        if(evt.getButton() == MouseEvent.BUTTON3){
            menuRightClick.show(textAreaInput, evt.getX(), evt.getY());
        } 
    }//GEN-LAST:event_textAreaInputMouseReleased

    private void menuShowHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShowHistoryActionPerformed
        //show history dialog
		int x = this.getLocationOnScreen().x - dialogHistory.getSize().width;
		if(x < 0){
			x = this.getLocationOnScreen().x + this.getSize().width;
		}
		int y = this.getLocationOnScreen().y;
		dialogHistory.setLocation(x, y);
        dialogHistory.setVisible(true);
    }//GEN-LAST:event_menuShowHistoryActionPerformed

    private void tableHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHistoryMouseReleased
        //put selected history item in textAreaChatHistory
        int row = tableHistory.getSelectedRow();
        String savedHistory = tableHistory.getModel().getValueAt(row, 1).toString();
		updateTextAreaConversation(savedHistory);
        
    }//GEN-LAST:event_tableHistoryMouseReleased

    private void dialogHistoryWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogHistoryWindowClosing
        //restore the incoming text
		updateTextAreaConversation(chatman.getAllMessagesText());
    }//GEN-LAST:event_dialogHistoryWindowClosing

    private void buttonNextHistoryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextHistoryPageActionPerformed
        
        try{
            historyPagination.nextPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            buttonPrevHistoryPage.setEnabled(historyPagination.hasPrev());
        }catch(SQLException e){
			CMHelper.getInstance().log("history next page failed: " + e.getMessage());
            message(CMHelper.getInstance().getStr("history_fail") + e.getMessage());
        }
    }//GEN-LAST:event_buttonNextHistoryPageActionPerformed

    private void buttonPrevHistoryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevHistoryPageActionPerformed

        try{
            historyPagination.prevPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            buttonPrevHistoryPage.setEnabled(historyPagination.hasPrev());
        }catch(SQLException e){
			CMHelper.getInstance().log("history prev page failed: " + e.getMessage());
            message(CMHelper.getInstance().getStr("history_fail") + e.getMessage());
        }
    }//GEN-LAST:event_buttonPrevHistoryPageActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        String aboutTitle = appTitle + " v" + version;
		String aboutContent  = CMHelper.getInstance().getStr("license");
		JOptionPane.showMessageDialog(null, aboutContent, aboutTitle, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuRemoteShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoteShutdownActionPerformed

		int answer = JOptionPane.showConfirmDialog(null, CMHelper.getInstance().getStr("remote_shutdown_message"), CMHelper.getInstance().getStr("remote_shutdown_title"), JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            CMMessage message = new CMMessage(CMMessage.TYPE_SHUTDOWN, "");
			chatman.sendMessage(message);
        }
    }//GEN-LAST:event_menuRemoteShutdownActionPerformed

    private void menuWakeOnLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWakeOnLanActionPerformed
        
		throw new UnsupportedOperationException("not supported yet");
		/*
		try{
			CMHelper.getInstance().sendWakeOnLan("remote_ip");
			
		}catch(IOException e){
			message(CMHelper.getInstance().getStr("wakeonlan_fail"));
		}
		*/
    }//GEN-LAST:event_menuWakeOnLanActionPerformed

    private void labelNextEmojiPageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextEmojiPageMouseReleased
        changeLabelIcon((JLabel)evt.getComponent(), "normal");
		nextEmojiPage();
    }//GEN-LAST:event_labelNextEmojiPageMouseReleased

    private void labelPrevEmojiPageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevEmojiPageMouseReleased
		changeLabelIcon((JLabel)evt.getComponent(), "normal");
		prevEmojiPage();
    }//GEN-LAST:event_labelPrevEmojiPageMouseReleased

    private void menuAbortLocalShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbortLocalShutdownActionPerformed
		try{
			CMHelper.getInstance().abortLocalShutdown();
			String info = "[INFO: REMOTE SHUTDOWN ABORTED BY USER]";
            final CMMessage message = new CMMessage(CMMessage.TYPE_TEXT, info);
			chatman.sendMessage(message);
		}catch(IOException e){
			CMHelper.getInstance().log("failed to abort local shutdown (from menu)");
			(new CmdShowError(CMHelper.getInstance().getStr("shutdown-abort-fail"))).execute();  // we don't need invokelater because we're on GUI
		}
    }//GEN-LAST:event_menuAbortLocalShutdownActionPerformed

    private void labelSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSendMousePressed
		changeLabelIcon((JLabel)evt.getComponent(), "pressed");
    }//GEN-LAST:event_labelSendMousePressed

    private void textAreaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaInputKeyPressed
		if (evt.getKeyChar() == '\n'){ 
			evt.consume();
            sendInputText();
        }
    }//GEN-LAST:event_textAreaInputKeyPressed

    private void menuAbortRemoteShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbortRemoteShutdownActionPerformed
		int answer = JOptionPane.showConfirmDialog(null, CMHelper.getInstance().getStr("abort_remote_shutdown_message"), CMHelper.getInstance().getStr("abort_remote_shutdown_title"), JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            final CMMessage message = new CMMessage(CMMessage.TYPE_ABORT_SHUTDOWN, "");
			chatman.sendMessage(message);
        }
    }//GEN-LAST:event_menuAbortRemoteShutdownActionPerformed

    private void textAreaConversationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaConversationMouseClicked

		if(evt.getButton() == MouseEvent.BUTTON1){
			return;
		}
		
		HTMLEditorKit kit = (HTMLEditorKit)textAreaConversation.getEditorKit();
		
		if(conversationPaneCssToggle == 1){
			kit.setStyleSheet(cssShowTime);
		}
		else{
			kit.setStyleSheet(cssHideTime);
		}
		
		String previousText = getConversationTextAll();
		textAreaConversation.setEditorKit(kit);
		textAreaConversation.setText(defaultTextAreaHtml);
		updateTextAreaConversation(previousText);

		conversationPaneCssToggle = 1 - conversationPaneCssToggle;
    }//GEN-LAST:event_textAreaConversationMouseClicked

    private void textAreaConversationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaConversationMouseEntered
		scrollPaneConversation.getVerticalScrollBar().removeAdjustmentListener(scrollListenerAlwaysDown);
    }//GEN-LAST:event_textAreaConversationMouseEntered

    private void scrollPaneConversationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollPaneConversationMouseEntered
        scrollPaneConversation.getVerticalScrollBar().removeAdjustmentListener(scrollListenerAlwaysDown);
    }//GEN-LAST:event_scrollPaneConversationMouseEntered

    private void labelSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSendMouseEntered
		changeLabelIcon((JLabel)evt.getComponent(), "hover");
    }//GEN-LAST:event_labelSendMouseEntered

    private void labelSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSendMouseExited
		changeLabelIcon((JLabel)evt.getComponent(), "normal");
    }//GEN-LAST:event_labelSendMouseExited

    private void labelClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMouseEntered
		changeLabelIcon((JLabel)evt.getComponent(), "hover");
    }//GEN-LAST:event_labelClearMouseEntered

    private void labelClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMouseExited
		changeLabelIcon((JLabel)evt.getComponent(), "normal");
    }//GEN-LAST:event_labelClearMouseExited

    private void labelPrevEmojiPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevEmojiPageMouseEntered
		changeLabelIcon((JLabel)evt.getComponent(), "hover");
    }//GEN-LAST:event_labelPrevEmojiPageMouseEntered

    private void labelPrevEmojiPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevEmojiPageMouseExited
        changeLabelIcon((JLabel)evt.getComponent(), "normal");
    }//GEN-LAST:event_labelPrevEmojiPageMouseExited

    private void labelNextEmojiPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextEmojiPageMouseEntered
		changeLabelIcon((JLabel)evt.getComponent(), "hover");
    }//GEN-LAST:event_labelNextEmojiPageMouseEntered

    private void labelNextEmojiPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextEmojiPageMouseExited
        changeLabelIcon((JLabel)evt.getComponent(), "normal");
    }//GEN-LAST:event_labelNextEmojiPageMouseExited

    private void labelSendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSendMouseReleased
        changeLabelIcon((JLabel)evt.getComponent(), "normal");
		sendInputText();
    }//GEN-LAST:event_labelSendMouseReleased

    private void labelPrevEmojiPageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevEmojiPageMousePressed
        changeLabelIcon((JLabel)evt.getComponent(), "pressed");
    }//GEN-LAST:event_labelPrevEmojiPageMousePressed

    private void labelNextEmojiPageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextEmojiPageMousePressed
        changeLabelIcon((JLabel)evt.getComponent(), "pressed");
    }//GEN-LAST:event_labelNextEmojiPageMousePressed

    private void labelClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMousePressed
        changeLabelIcon((JLabel)evt.getComponent(), "pressed");
    }//GEN-LAST:event_labelClearMousePressed

    private void dialogHistoryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dialogHistoryComponentShown
		
		//is run everytime history dialog shows 
        historyPagination = new HistoryTablePagination(
                tableHistory,
                "history.sqlite",
                "SELECT date,text FROM chat_sessions ORDER BY date DESC"
        );

        try{
            historyPagination.nextPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            
        }catch(SQLException e){
			CMHelper.getInstance().log("failed to show history window: " + e.getMessage());
            message(CMHelper.getInstance().getStr("history_fail") + e.getMessage());
        }
		
    }//GEN-LAST:event_dialogHistoryComponentShown
		
	//ye labele makhfi ke vaghti mouse az textarea bala biroon miad scrollo dorost kone
    private void labelMouseDetectorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseDetectorMouseEntered
		//fix scroll only if mouse is entering from the top
		int y = evt.getY();
		if(y<10){
			fixConvoScroll();
		}
    }//GEN-LAST:event_labelMouseDetectorMouseEntered

    private void menuChooseThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChooseThemeActionPerformed
		
		//set things to default
		dropdownBgs.removeAllItems();
		themeChooserSelectedTheme = null;
		labelPopupPrev.setIcon(null);
		labelBgPrev.setIcon(null);
		
		try{
			File themesDir = new File(CMConfig.getInstance().get("themes-dir", CMConfig.DEFAULT_THEMES_DIR));
			Files.list(themesDir.toPath()).forEach((Path t) -> {
				String[] s = t.getFileName().toString().split("\\.");
				String extension = s[s.length-1];
				if("cmtheme".equals(extension) || "zip".equals(extension)){
					dropdownBgs.addItem(t.getFileName().toString());
				}
			});
			dialogChooseBg.setLocationRelativeTo(null);
			dialogChooseBg.setVisible(true);
			
		}catch(Exception e){
			message(CMHelper.getInstance().getStr("themes_folder_open_fail"));
			CMHelper.getInstance().log("failed to get list of themes: " + e.getMessage());
		}
    }//GEN-LAST:event_menuChooseThemeActionPerformed

    private void dropdownBgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownBgsActionPerformed
		
		if(dropdownBgs.getSelectedItem() == null){
			return;
		}
		
		try{
			String themeName = (String) dropdownBgs.getSelectedItem();
			themeChooserSelectedTheme = CMTheme.getFromDefaultDir(themeName);
			Image bg = themeChooserSelectedTheme.getBgImage().getImage().getScaledInstance(
					330, 400, Image.SCALE_SMOOTH);
			
			labelBgPrev.setIcon(new ImageIcon(bg));
			labelPopupPrev.setIcon(themeChooserSelectedTheme.getPopupImage());
			labelThemeName.setText(themeChooserSelectedTheme.getUsername());
		}catch(Exception e ){
			message("Bad theme file");
			CMHelper.getInstance().log("bad theme file selected: " + e.getMessage());
		}
    }//GEN-LAST:event_dropdownBgsActionPerformed

    private void buttonSelectBgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectBgActionPerformed
        currentTheme = themeChooserSelectedTheme;
		applyCurrentTheme();
		CMConfig.getInstance().set("theme", currentTheme.getFileName());
		CMConfig.getInstance().save();
    }//GEN-LAST:event_buttonSelectBgActionPerformed

    private void dialogChooseBgWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogChooseBgWindowClosing

    }//GEN-LAST:event_dialogChooseBgWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

		do_pregui_check();

        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


		/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChatFrame frame = ChatFrame.getInstance();
				//in tartib bayad bashe hatman
                frame.initialize();
				frame.startChatman();
            }
        });
    }
	
	//TODO: vaghti barname ii ba file reside associate nashode error mide
	//bejash folder ro baz konim dar in halat
	private static void do_pregui_check(){
		//send a showgui message to localhost, if localhost responds we exit
		CMMessage showGuiMessage = new CMMessage(CMMessage.TYPE_SHOWGUI, "", "", "", 0);
		List<NameValuePair> postParams = new ArrayList<>();
		postParams.add(new BasicNameValuePair("message", showGuiMessage.getAsJsonString()));
		HttpEntity postData = new UrlEncodedFormEntity(postParams, Charset.forName("UTF-8"));
		String port = CMConfig.getInstance().get("server-port", CMConfig.DEFAULT_SERVER_PORT);
		HttpPost post = new HttpPost("http://127.0.0.1:"+port);
		post.setEntity(postData);
		try (CloseableHttpClient httpClient = HttpClientBuilder.create().build(); CloseableHttpResponse response = httpClient.execute(post)) {
			int code = response.getCode();
			EntityUtils.consume(response.getEntity());
			//if localhost responds we exit
			if(code == 200){
				System.exit(0);
			}
		}catch(Exception e){}
	}
     

    public void initialize(){

		// Checks if history.sqlite exists and if not tries to create it
		try{
			CMHelper.getInstance().checkDatabaseFile();
		}catch(Exception e){
			(new CmdFatalErrorExit("history database cannot be created", e)).execute();
		}
		
        // Locale
		CMHelper.getInstance().setLocale(CMConfig.getInstance().getLocale());
		
		// !!! DO NOT MOVE THE ABOVE CODE BELOW THEY HAVE TO BE RUN FIRST !!!
		
		this.setTitle(appTitle);
		
		createTrayIcons();
		
		// Show tray if config says yes
		if(CMConfig.getInstance().get("show-tray-icon", CMConfig.DEFAULT_SHOWTRAY).equals("yes")){
			setTrayIconVisible(trayIconApp, true);
		}
		
        // TextArea drag-n-drop
        textAreaInput.setDropTarget(new DropTarget() {
			@Override
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) evt.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    for (File file : droppedFiles) {
                        //check file size
                        int max = Integer.valueOf(CMConfig.getInstance().get("max-file-size", CMConfig.DEFAULT_FILEDROP_SIZEWARNING));
                        if(file.length()> max*1000*1000){
                            int choice = JOptionPane.showConfirmDialog(null, CMHelper.getInstance().getStr("file_big_warning"), CMHelper.getInstance().getStr("file_big_title"), JOptionPane.YES_NO_OPTION);
							if(choice == JOptionPane.NO_OPTION){
								//skip this file
								continue;
							}
                        }
                        //send the file
						String filePath = file.getAbsolutePath();
						String fileName = file.getName();
						final CMMessage fileMessage = new CMMessage(CMMessage.TYPE_FILE, fileName);
						fileMessage.putMiscData("file_path", filePath);
						//avoid getting a notification sound when dragging the file because window gets out of focus
						ChatFrame.getInstance().toFront();
						chatman.sendMessage(fileMessage);
                    }
                } catch (Exception ex) {
                    message(CMHelper.getInstance().getStr("open_file_fail"));
                }
            }
        });

        // TextArea right click
		
        //create a paste action to replace the default one because the default copoies styles/html too
        Action pasteAction = new AbstractAction(CMHelper.getInstance().getStr("paste")) {
            @Override
            public void actionPerformed(ActionEvent e) {
				//only raw text is pasted in a textfield with no styles/html
				JTextField tempField = new JTextField();
				tempField.paste();
				String pastedText = tempField.getText();
				//agar ax darim faghat akhar paste kon chon nemish
				if(getInputText().contains("<img")){
					updateInputText(pastedText, true);
					return;
				}
				//vaghti yek ghesmat as text select shode va mikhaim oonja paste konim				
				String selectedText = textAreaInput.getSelectedText();
				if(selectedText!=null && !selectedText.isEmpty()){
					String currentText = textAreaInput.getText();
					currentText = currentText.replace(selectedText, pastedText);
					textAreaInput.setText(currentText);
					return;
				}
				//vaghti vasate text paste mikonim
				int currentCaretPos = textAreaInput.getCaretPosition();
				textAreaInput.setCaretPosition(textAreaInput.getDocument().getLength());
				int lastCaretPos = textAreaInput.getCaretPosition();
				if(currentCaretPos != lastCaretPos){
					String currentText = getInputText();
					String firstHalf = currentText.substring(0, currentCaretPos-1);
					String secondHalf = currentText.substring(currentCaretPos-1, currentText.length());
					updateInputText(firstHalf+pastedText+secondHalf, false);
					textAreaInput.setCaretPosition(currentCaretPos + pastedText.length());
					return;
				}
				//vaghti akhare text paste mikonim
				updateInputText(pastedText, true);
				
            }
        };
		
		//replace default paste action with our own
		ActionMap map = textAreaInput.getActionMap();
		map.put(DefaultEditorKit.pasteAction, pasteAction);
		       
        //get default copy and cut actions
        Action copyAction = textAreaInput.getActionMap().get(DefaultEditorKit.copyAction);
        copyAction.putValue("Name", CMHelper.getInstance().getStr("copy"));
        Action cutAction = textAreaInput.getActionMap().get(DefaultEditorKit.cutAction);
        cutAction.putValue("Name", CMHelper.getInstance().getStr("cut"));
		
		//add copy/cut/paste actions to our right click menu
        menuRightClick.add (pasteAction); 
        menuRightClick.add (copyAction);
        menuRightClick.add (cutAction);

        // TextArea cursor
        ((HTMLEditorKit)textAreaInput.getEditorKit()).setDefaultCursor(new Cursor(Cursor.TEXT_CURSOR));
        
        // Input focus
        textAreaInput.requestFocus();

        // Table BG transparent
        tableEmojis.setBackground(new Color(0,0,0,0));  
		tableEmojis.setGridColor(new Color(0,0,0,0));
        
        // Populate Table
        //!!!IMPORTANT: only words in emoticons name 
        //!!!IMPORTANT: emoticons should have .gif extention and be stored in /resources/emoticons folder
        //!!!IMPORTANT: any change made here, or to emoticons names,format,folder,etc. should be also applied to regular expression accross the code
        emoticonsArray = new String[][][]{
			{
				{"hi", "smoke", "xd", "amazing", "victory"},
				{"bleed", "desperate", "spiral", "shake", "shooting"},
				{"calmdownwide", "killwide", "getout", "wallbangwide", "extraordinary"},
				{"yes", "grumpyno", "grumpy", "dog", "epicface"},
				{"snail", "wifi", "reset", "power", "question"}
			},
			{
				{"badluck", "ballerina", "boring", "dancing", "dizzy"},
				{"dunno", "exorcist", "flying", "happiness", "dancingg"},
				{"happyy", "help", "killme", "killmyself", "looser"},
				{"magic", "dreaming", "nah", "nono", "patpat"},
				{"poking", "scratching", "sleeping", "smooth", "stars"}
			},
			{
				{"steal", "taichi", "teehee", "what", "yeah"},
				{"yesss", "yipee", "dancingg", "bat", "na"},
				{"null", "null", "null", "null", "null"},
				{"null", "null", "null", "null", "null"},
				{"null", "null", "null", "null", "null"}
			}
        };
		nextEmojiPage();
		
        // Theme
		try{
			String themeName = CMConfig.getInstance().get("theme", CMConfig.DEFAULT_THEME);
			currentTheme = CMTheme.getFromDefaultDir(themeName);
		}catch(Exception e){
			CMHelper.getInstance().log("getting theme failed. getting default theme");
			currentTheme = CMTheme.getDefaultTheme();
		}
		applyCurrentTheme();
       
		// CSS for conversation pane 
		cssHideTime = new StyleSheet();
		cssShowTime = new StyleSheet();
		cssHideTime.addRule(".time{font-size:0px;color:#3a3a3a}");
		cssShowTime.addRule(".time{font-size:11px}");
		
        // Empty HTML Texts
        defaultTextAreaHtml = "<html><head><style type='text/css'>#text { color: "+ textColor +"; font-family: Tahoma; font-size: 12px; }</style></head><body id='text'></body></html>";
		HTMLEditorKit tkit = (HTMLEditorKit)textAreaConversation.getEditorKit();
		tkit.setStyleSheet(cssHideTime);
		textAreaConversation.setEditorKit(tkit);		
        textAreaInput.setText(defaultTextAreaHtml);
		textAreaConversation.setText(defaultTextAreaHtml);
        
        // Make ScrollPanes invisible
        scrollPaneInput.setOpaque(false);
        scrollPaneInput.getViewport().setOpaque(false);
        scrollPaneConversation.setOpaque(false);
        scrollPaneConversation.getViewport().setOpaque(false);
		
		// To fix the scrolls
		scrollListenerAlwaysDown = new AdjustmentListener() {  
			public void adjustmentValueChanged(AdjustmentEvent e) {  
				e.getAdjustable().setValue(e.getAdjustable().getMaximum());  
			}
		};	
		
		// Customized scrollbar
		JScrollBar scrollbar = scrollPaneConversation.getVerticalScrollBar();
		scrollbar.setOpaque(false);
		int defaultHeight = scrollbar.getPreferredSize().height;
		scrollbar.setPreferredSize(new Dimension(10, defaultHeight));
		scrollbar.setUI(new CMScrollbarUI());
		
        // Application icon
        Toolkit toolkit = Toolkit.getDefaultToolkit();	
		ArrayList<Image> icons = new ArrayList<Image>();
		Image icon48 = toolkit.createImage(getClass().getResource("/resources/icon48.png"));
		Image icon32 = toolkit.createImage(getClass().getResource("/resources/icon32.png"));
		Image icon24 = toolkit.createImage(getClass().getResource("/resources/icon24.png"));
		icons.add(icon48);
		icons.add(icon32);
		icons.add(icon24);
		this.setIconImages(icons);
		
        // History dialog
        URL urlHistory = getClass().getResource("/resources/icon_history.png");
        Image historyIcon = toolkit.createImage(urlHistory);
        dialogHistory.setIconImage(historyIcon);
		
		// Theme choose dialog
		URL urlThemeChoose = getClass().getResource("/resources/icon16.png");
        Image themeChooseIcon = toolkit.createImage(urlThemeChoose);
		dialogChooseBg.setIconImage(themeChooseIcon);
		
		// Hide text column in history table
		tableHistory.removeColumn(tableHistory.getColumnModel().getColumn(1));

        // Center
        this.setLocationRelativeTo(null);
		
		// Hide wake on lan menu
		menuWakeOnLan.setVisible(false);

		// Iransans font for everything
		try{
			InputStream is = getClass().getResourceAsStream("/resources/iransans.ttf");
			Font font = Font.createFont(Font.TRUETYPE_FONT, is);
			Font iranSans = font.deriveFont(12f);
			menuFile.setFont(iranSans);
			menuChooseTheme.setFont(iranSans);
			menuShowHistory.setFont(iranSans);
			menuRemoteShutdown.setFont(iranSans);
			menuAbortRemoteShutdown.setFont(iranSans);
			menuAbortLocalShutdown.setFont(iranSans);
			menuAbout.setFont(iranSans);
			menuExit.setFont(iranSans);
			labelStatus.setFont(iranSans);
			labelStatusLabl.setFont(iranSans);
			tableHistory.setFont(iranSans);
		}catch(Exception e){
			//font will revert to Tahoma
		}
		
		// Hide progressbar
		progressBar.setVisible(false);
		
    } 
    
    // Start Chatman
    public void startChatman(){	
		try{
			chatman = new Chatman();
			chatman.start();
		}catch(Exception e){
			final Exception ex = e;
			String error = "Could not start server: " + e.getMessage();
			(new CmdFatalErrorExit(error, ex)).execute();
		}
    }
    
    // Called from myInits()
	public void createTrayIcons(){

        if (!SystemTray.isSupported()) {
			CMHelper.getInstance().log("System tray not supported");
            return;
        }
				
		ImageIcon appIcon = new ImageIcon(getClass().getResource("/resources/icon16.png"));
		ImageIcon newMessageIcon = new ImageIcon(getClass().getResource("/resources/new-message16.png"));
        trayIconApp = new TrayIcon(appIcon.getImage());
		trayIconNewMessage = new TrayIcon(newMessageIcon.getImage());
		
		trayIconApp.setImageAutoSize(false);
		trayIconApp.setToolTip(appTitle);
		trayIconNewMessage.setImageAutoSize(false);
		trayIconNewMessage.setToolTip(CMHelper.getInstance().getStr("new_message"));
		
        // create a right-click menu 
		PopupMenu rclickMenu = new PopupMenu();
        MenuItem openItem = new MenuItem("Open");
        MenuItem exitItem = new MenuItem("Exit");
        rclickMenu.add(openItem);
        rclickMenu.add(exitItem);
        trayIconApp.setPopupMenu(rclickMenu);
		
		//create actions
		ActionListener actionOpen = new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				popopClicked(MouseEvent.BUTTON1);
			}
		};
		ActionListener actionExit = new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				exit(0);
			}
		};
		
		//add actions to items and double-click
		trayIconApp.addActionListener(actionOpen);
		openItem.addActionListener(actionOpen);
		exitItem.addActionListener(actionExit);
		trayIconNewMessage.addActionListener(actionOpen);
		
	}
	
	public void setTrayIconVisible(TrayIcon trayIcon, boolean visible){
        try {
			SystemTray systemTray = SystemTray.getSystemTray();
			if(visible){
				systemTray.add(trayIcon);
			}
			else{
				systemTray.remove(trayIcon);
			}
        } catch (AWTException e) {
			CMHelper.getInstance().log("Tray icon could not be added");
        }
	}
	
    public void setupGUITexts(){
        dialogHistory.setTitle(CMHelper.getInstance().getStr("history"));
        buttonNextHistoryPage.setText(CMHelper.getInstance().getStr("next_page"));
        buttonPrevHistoryPage.setText(CMHelper.getInstance().getStr("prev_page"));
        labelStatusLabl.setText(CMHelper.getInstance().getStr("status"));
        labelStatus.setText(CMHelper.getInstance().getStr("offline"));
        menuFile.setText(CMHelper.getInstance().getStr("options"));
        menuChooseTheme.setText(CMHelper.getInstance().getStr("choose_theme"));
        menuShowHistory.setText(CMHelper.getInstance().getStr("show_history"));
		menuRemoteShutdown.setText(CMHelper.getInstance().getStr("remote_shutdown"));
		menuAbortLocalShutdown.setText(CMHelper.getInstance().getStr("abort_local_shutdown"));
		menuAbortRemoteShutdown.setText(CMHelper.getInstance().getStr("abort_remote_shutdown"));
		menuWakeOnLan.setText(CMHelper.getInstance().getStr("wakeonlan"));
        menuAbout.setText(CMHelper.getInstance().getStr("about"));
        menuExit.setText(CMHelper.getInstance().getStr("exit"));
    }
	
	public void changeLabelIcon(JLabel label, String state){
		
		if(state == null){
			state = "normal";
		}
		else if(state.isEmpty()){
			state = "normal";
		}
		String template = "/resources/label-*name*-*theme*-*state*.png";
		String path = "";
		
		if(label == labelSend){
			path = template.replace("*name*", "send").replace("*theme*", labelsTheme).replace("*state*", state);
		}
		else if(label == labelClear){
			path = template.replace("*name*", "clear").replace("*theme*", labelsTheme).replace("*state*", state);
		}
		else if(label == labelPrevEmojiPage){
			path = template.replace("*name*", "prev").replace("*theme*", labelsTheme).replace("*state*", state);
		}
		else if(label == labelNextEmojiPage){
			path = template.replace("*name*", "next").replace("*theme*", labelsTheme).replace("*state*", state);
		}
		else if(label == labelConvoBg){
			path = template.replace("*name*", "top").replace("*theme*", textAreasTheme).replace("*state*", state);
		}
		else if(label == labelInputBg){
			path = template.replace("*name*", "bottom").replace("*theme*", textAreasTheme).replace("*state*", state);
		}
		else if(label == labelTableBg){
			path = template.replace("*name*", "table").replace("*theme*", textAreasTheme).replace("*state*", state);
		}
		
		ImageIcon icon = (new ImageIcon(getClass().getResource(path)));
		label.setIcon(icon);
		
	}
	
	//populates a table with emoticons and returns the table model
	public AbstractTableModel getEmoticonTable(String[][] emoticonsArray){
		
			//make table cells uneditable
			AbstractTableModel model = new DefaultTableModel(5, 5){
				@Override
				public boolean isCellEditable(int row, int column){
					return false;
				}
			};

			//add emoticons to cells
			for(int row = 0;row<5;row++){
				for(int col = 0;col<5;col++){
					String name = emoticonsArray[row][col];
					URL url = getClass().getResource("/resources/emoticons/" + name + ".gif");
					String html;
					if(url == null){
						html = "<html></html>";
					}
					else{
						html = "<html><img src='" + url.toString() + "' /></html>";
					}
					model.setValueAt(html, row, col);
				}
			}
			
			return model;
	}
	
	//loads next set of emojis
	public void nextEmojiPage(){
		
		if(emojisIndex >= (emoticonsArray.length - 1) ){
			emojisIndex = 0;
		}
		else{
			emojisIndex++;
		}
		
		AbstractTableModel model = getEmoticonTable(emoticonsArray[emojisIndex]);
		tableEmojis.setModel(model);
		
	}
	
	//loads previous set of emojis
	public void prevEmojiPage(){
		
		if(emojisIndex <= 0){
			emojisIndex = (emoticonsArray.length -1);
		}
		else{
			emojisIndex--;
		}
		
		AbstractTableModel model = getEmoticonTable(emoticonsArray[emojisIndex]);
		tableEmojis.setModel(model);
		
	}

    //sends the content of textAreaInput
    private void sendInputText(){
		
		fixConvoScroll();
    
        String text = getInputText();
        
        //return if input is empty
        if(text.isEmpty())
            return;

		final CMMessage message = new CMMessage(CMMessage.TYPE_TEXT, text);
		chatman.sendMessage(message);

		clearInputText();

    }
    
    //adds a message to messages history and shows it in conversation panel
    //it is called both when we sendInputText a message or receive a message
    public void showMessage(CMMessage message){
		
		//don't do anything for ping and other shit messages
		if(message.getDisplayableContent().isEmpty()){
			return;
		}
		
		updateTextAreaConversation(chatman.getAllMessagesText());
		
		//check peer theme
		if(!message.isOurMessage()){
			try{
				if(!peerTheme.getFileName().equals(message.getSenderTheme())){
					peerTheme = CMTheme.getFromDefaultDir(message.getSenderTheme());
					setPeerTheme(peerTheme);
				}
			}catch(Exception e){
				CMMessage themeReqMsg = new CMMessage(CMMessage.TYPE_REQUEST_THEME_FILE, "");
				OutgoingMsgHandler handler = new OutgoingMsgHandler(themeReqMsg);
				handler.handle();
				return;
			}
		}

		if(!message.isOurMessage()){
			showNewMessagePopup();
		}
			
    }
	 
	private void updateTextAreaConversation(String text){
        String html = textAreaConversation.getText();
		Document doc = Jsoup.parse(html);
		Element textDiv = doc.select("body#text").first();
		if(textDiv == null){
			(new CmdInvokeLater(new CmdFatalErrorExit("tell pouria he has fucked up with the jsoup idea", (new Exception())))).execute();
		}
		textDiv.html(text);
		textAreaConversation.setText(doc.outerHtml());
	}
	  
    //is called when we want to add something to the outgoing text like emoticons, paste stuff
    public void updateInputText(String t, boolean append){
        String html = textAreaInput.getText();
		Document doc = Jsoup.parse(html);
		Element textDiv = doc.select("body#text").first();
		if(textDiv == null){
			(new CmdInvokeLater(new CmdFatalErrorExit("tell pouria he has fucked up with the jsoup idea", (new Exception())))).execute();
		}
		if(append){
			textDiv.append(t);
		}
		else{
			textDiv.html(t);
		}
		textAreaInput.setText(doc.outerHtml());
    }
    
    public String getInputText(){
        String html = textAreaInput.getText();
		Document doc = Jsoup.parse(html);
		Element textDiv = doc.select("body#text").first();
		if(textDiv == null){
			(new CmdInvokeLater(new CmdFatalErrorExit("tell pouria he has fucked up with the jsoup idea", (new Exception())))).execute();
		}		
		return textDiv.html();
    }
	
    public String getConversationTextAll(){
        String html = textAreaConversation.getText();
		Document doc = Jsoup.parse(html);
		Element textDiv = doc.select("body#text").first();
		if(textDiv == null){
			(new CmdInvokeLater(new CmdFatalErrorExit("tell pouria he has fucked up with the jsoup idea", (new Exception())))).execute();
		}		
		return textDiv.html();
    }
    
    public void clearInputText(){
        updateInputText("", false);
    }
	
	private void fixConvoScroll(){
		//fix for scroll
		int listenersCount = scrollPaneConversation.getVerticalScrollBar().getAdjustmentListeners().length;
		if(listenersCount == 0){
			scrollPaneConversation.getVerticalScrollBar().addAdjustmentListener(scrollListenerAlwaysDown);
		}
	}
	
	public void updateProgressBar(int progress){
		if(progress == 100){
			progressBar.setVisible(false);
		}
		else{
			progressBar.setVisible(true);
			progressBar.setValue(progress);
		}
	}
    
	public void applyCurrentTheme(){
		
		labelFrameBg.setIcon(currentTheme.getBgImage());
		newMessagePopup = new CMNotifPopup(currentTheme);
		username = currentTheme.getUsername();
				
		//set up theme
		labelsTheme = currentTheme.getButtonsTheme();
		textAreasTheme = currentTheme.getTextAreasTheme();
		
		//set text color
		textColor = (textAreasTheme.equals("dark"))? TEXTCOLOR_LIGHT : TEXTCOLOR_DARK;
		//input caret color according to text color
		textAreaInput.setCaretColor(Color.getColor(textColor));

		//set label icons
		changeLabelIcon(labelConvoBg, "");
		changeLabelIcon(labelInputBg, "");
		changeLabelIcon(labelTableBg, "");
		changeLabelIcon(labelSend, "");
		changeLabelIcon(labelClear, "");
		changeLabelIcon(labelPrevEmojiPage, "");
		changeLabelIcon(labelNextEmojiPage, "");
	}

	public String getUserName(){
		return this.username;
	}
	   
    //gives us the hero that we don't deserve
    public Chatman getChatmanInstance(){
        return chatman;
    }
	
	public void popopClicked(int mouseButton){
        //close the "New Message" popup and show the application window
        newMessagePopup.hide();
		//if click show windows else just hide popup
		if(mouseButton == MouseEvent.BUTTON1){
			//Show
			showWindow();
			//Focus
			textAreaInput.requestFocus();
		}
		else{
			setTrayIconVisible(trayIconNewMessage, true);
		}
	}
	
	public void showNewMessagePopup(){
		//popup and play sound if we're hidden
		if(!this.isVisible() && !newMessagePopup.isVisible()){
            newMessagePopup.show();
			newMessagePopup.playSound();
        }
        //bleep only if we received message and was not focused
        else if(!this.isActive()){
            newMessagePopup.playSound();
        }
	}
	
	public CMTheme getCurrentTheme(){
		return currentTheme;
	}
	
	public CMTheme getPeerTheme(){
		return peerTheme;
	}
	
	public void setPeerTheme(CMTheme peerTheme){
		this.peerTheme = peerTheme;
		newMessagePopup = new CMNotifPopup(peerTheme);
	}

    //sets the status label at the bottom
    public void setLabelStatus(String s){
        labelStatus.setText(s);
		setTrayIconText(s);
    }
	
	//sets tray icon tooltip text
	public void setTrayIconText(String s){
		trayIconApp.setToolTip(s);
	}
    
    //shows a message
    public void message(String m){
        m = "<html><span style='font-size:14px;'>" + m + "</span></html>";
        JOptionPane.showMessageDialog(null, m);
    } 
	
	//shows loading gif
	public void changeStatusIcon(String iconName){
		labelStatusIcon.setIcon((new ImageIcon(getClass().getResource("/resources/"+iconName))));
	}
	
	public String getTextColor(){
		return this.textColor;
	}
	  	
	//hides the chatman windows
	public void hideWindow(){
		//this.setVisible(false);
		//apparently it's better to use dispose because it releases all resources
		this.dispose();
	}
	
	//shows the chatman window
	public void showWindow(){
		this.setVisible(true);
		//maximize
		if(this.getExtendedState() == ICONIFIED){
			this.setExtendedState(NORMAL);
		}
		//remove new message tray icon
		setTrayIconVisible(trayIconNewMessage, false);
	}
	
	
    //the end of chatman. that's it. no auto pilot :(
    public synchronized void exit(int exitCode){
        chatman.saveHistory();
        CMConfig.getInstance().save();
        System.exit(exitCode);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNextHistoryPage;
    private javax.swing.JButton buttonPrevHistoryPage;
    private javax.swing.JButton buttonSelectBg;
    private javax.swing.JDialog dialogChooseBg;
    private javax.swing.JDialog dialogHistory;
    private javax.swing.JComboBox<String> dropdownBgs;
    private javax.swing.JLabel labelBgPrev;
    private javax.swing.JLabel labelClear;
    private javax.swing.JLabel labelConvoBg;
    private javax.swing.JLabel labelFrameBg;
    private javax.swing.JLabel labelInputBg;
    private javax.swing.JLabel labelMouseDetector;
    private javax.swing.JLabel labelNextEmojiPage;
    private javax.swing.JLabel labelPopupPrev;
    private javax.swing.JLabel labelPrevEmojiPage;
    private javax.swing.JLabel labelSend;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStatusBackground;
    private javax.swing.JLabel labelStatusIcon;
    private javax.swing.JLabel labelStatusLabl;
    private javax.swing.JLabel labelTableBg;
    private javax.swing.JLabel labelThemeName;
    private javax.swing.JMenuItem menuAbortLocalShutdown;
    private javax.swing.JMenuItem menuAbortRemoteShutdown;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuChooseTheme;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuRemoteShutdown;
    private javax.swing.JPopupMenu menuRightClick;
    private javax.swing.JPopupMenu.Separator menuSeparator1;
    private javax.swing.JPopupMenu.Separator menuSeparator2;
    private javax.swing.JMenuItem menuShowHistory;
    private javax.swing.JMenuItem menuWakeOnLan;
    private javax.swing.JMenuBar menubarMain;
    private javax.swing.JPanel panelChooseBg;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPaneConversation;
    private javax.swing.JScrollPane scrollPaneHistory;
    private javax.swing.JScrollPane scrollPaneInput;
    private javax.swing.JTable tableEmojis;
    private javax.swing.JTable tableHistory;
    private javax.swing.JEditorPane textAreaConversation;
    private javax.swing.JEditorPane textAreaInput;
    // End of variables declaration//GEN-END:variables
}
