/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pouria.chatman.gui;

import com.pouria.chatman.Chatman;
import com.pouria.chatman.ChatmanMessage;
import com.pouria.chatman.Helper;
import com.pouria.chatman.classes.HistoryTablePagination;
import com.pouria.chatman.connection.HttpClient;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.SQLException;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;
import javax.swing.event.HyperlinkEvent;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author PouriaP
 * 
 * This file has the main() function and is the entry point of the application
 * 
 */
public class ChatFrame extends javax.swing.JFrame {

    private static ChatFrame instance = null; 
    private Chatman chatman;
    private String[] defaultTextAreaHtml;
    private String incomingTextAll = "";
    private String textAreaIncomingContentBeforeHistory = "";
    private HistoryTablePagination historyPagination;
	private String[][][] emoticonsArray;
	private int emojisIndex = -1; //-1 chon bare avval mikhaim bere be 0
	private String username;
	PopupDialog newMessagePopup;
	
    
    private ChatFrame(){
        initComponents();
    }
    
    
    public static ChatFrame getInstance(){
        if(instance == null)
            instance = new ChatFrame();
        
        return instance;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPopupNormal = new com.pouria.chatman.gui.PopupDialog();
        panelPopupNormal = new javax.swing.JPanel();
        labelNewMessage = new javax.swing.JLabel();
        labelMessageIcon = new javax.swing.JLabel();
        menuRightClick = new javax.swing.JPopupMenu();
        dialogHistory = new javax.swing.JDialog();
        scrollPaneHistory = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        buttonNextHistoryPage = new javax.swing.JButton();
        buttonPrevHistoryPage = new javax.swing.JButton();
        dialogPopupBat = new com.pouria.chatman.gui.PopupDialog();
        labelBat = new javax.swing.JLabel();
        scrollPaneIncoming = new javax.swing.JScrollPane();
        textAreaIncoming = new javax.swing.JEditorPane();
        scrollPaneOutgoing = new javax.swing.JScrollPane();
        textAreaOutgoing = new javax.swing.JEditorPane();
        incomingBg = new javax.swing.JLabel();
        outgoingBg = new javax.swing.JLabel();
        tableEmojis = new javax.swing.JTable();
        labelNextEmojiPage = new javax.swing.JLabel();
        labelPrevEmojiPage = new javax.swing.JLabel();
        labelSend = new javax.swing.JLabel();
        labelClear = new javax.swing.JLabel();
        labelStatusLabl = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        backgroundOfLabels = new javax.swing.JLabel();
        labelFrameBg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuChangeBg = new javax.swing.JMenuItem();
        menuShowHistory = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuRemoteShutdown = new javax.swing.JMenuItem();
        menuAbortRemoteShutdown = new javax.swing.JMenuItem();
        menuAbortLocalShutdown = new javax.swing.JMenuItem();
        menuWakeOnLan = new javax.swing.JMenuItem();
        menuSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        dialogPopupNormal.setAlwaysOnTop(true);
        dialogPopupNormal.setMinimumSize(new java.awt.Dimension(180, 60));
        dialogPopupNormal.setResizable(false);

        panelPopupNormal.setBackground(new java.awt.Color(102, 102, 102));
        panelPopupNormal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPopupNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPopupNormal.setName(""); // NOI18N
        panelPopupNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelPopupNormalMouseReleased(evt);
            }
        });

        labelNewMessage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNewMessage.setForeground(new java.awt.Color(231, 231, 231));
        labelNewMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNewMessage.setText("پیام جدید");

        labelMessageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new_message_50x50.png"))); // NOI18N

        javax.swing.GroupLayout panelPopupNormalLayout = new javax.swing.GroupLayout(panelPopupNormal);
        panelPopupNormal.setLayout(panelPopupNormalLayout);
        panelPopupNormalLayout.setHorizontalGroup(
            panelPopupNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPopupNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMessageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNewMessage)
                .addGap(16, 16, 16))
        );
        panelPopupNormalLayout.setVerticalGroup(
            panelPopupNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMessageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPopupNormalLayout.createSequentialGroup()
                .addComponent(labelNewMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogPopupNormalLayout = new javax.swing.GroupLayout(dialogPopupNormal.getContentPane());
        dialogPopupNormal.getContentPane().setLayout(dialogPopupNormalLayout);
        dialogPopupNormalLayout.setHorizontalGroup(
            dialogPopupNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPopupNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPopupNormalLayout.setVerticalGroup(
            dialogPopupNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPopupNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuRightClick.setBackground(new java.awt.Color(51, 51, 51));
        menuRightClick.setForeground(new java.awt.Color(255, 255, 255));

        dialogHistory.setTitle("تاریخچه");
        dialogHistory.setAlwaysOnTop(true);
        dialogHistory.setIconImage(null);
        dialogHistory.setMinimumSize(new java.awt.Dimension(400, 300));
        dialogHistory.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogHistoryWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogHistoryWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dialogHistoryWindowOpened(evt);
            }
        });

        tableHistory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تاریخ", "متن"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableHistory.setRowHeight(20);
        tableHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableHistoryMouseReleased(evt);
            }
        });
        scrollPaneHistory.setViewportView(tableHistory);

        buttonNextHistoryPage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonNextHistoryPage.setText("صفحه بعد");
        buttonNextHistoryPage.setEnabled(false);
        buttonNextHistoryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextHistoryPageActionPerformed(evt);
            }
        });

        buttonPrevHistoryPage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonPrevHistoryPage.setText("صفحه قبل");
        buttonPrevHistoryPage.setEnabled(false);
        buttonPrevHistoryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevHistoryPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogHistoryLayout = new javax.swing.GroupLayout(dialogHistory.getContentPane());
        dialogHistory.getContentPane().setLayout(dialogHistoryLayout);
        dialogHistoryLayout.setHorizontalGroup(
            dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogHistoryLayout.createSequentialGroup()
                        .addComponent(buttonPrevHistoryPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNextHistoryPage))
                    .addComponent(scrollPaneHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogHistoryLayout.setVerticalGroup(
            dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNextHistoryPage)
                    .addComponent(buttonPrevHistoryPage))
                .addContainerGap())
        );

        dialogPopupBat.setAlwaysOnTop(true);
        dialogPopupBat.setMinimumSize(new java.awt.Dimension(400, 300));
        dialogPopupBat.setResizable(false);

        labelBat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bat.gif"))); // NOI18N
        labelBat.setText("jLabel1");
        labelBat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBat.setMaximumSize(new java.awt.Dimension(400, 300));
        labelBat.setMinimumSize(new java.awt.Dimension(400, 300));
        labelBat.setPreferredSize(new java.awt.Dimension(400, 300));
        labelBat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBatMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout dialogPopupBatLayout = new javax.swing.GroupLayout(dialogPopupBat.getContentPane());
        dialogPopupBat.getContentPane().setLayout(dialogPopupBatLayout);
        dialogPopupBatLayout.setHorizontalGroup(
            dialogPopupBatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBat, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        dialogPopupBatLayout.setVerticalGroup(
            dialogPopupBatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBat, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chatman Rises");
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(500, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        scrollPaneIncoming.setOpaque(false);

        textAreaIncoming.setEditable(false);
        textAreaIncoming.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textAreaIncoming.setContentType("text/html"); // NOI18N
        textAreaIncoming.setAutoscrolls(false);
        textAreaIncoming.setOpaque(false);
        textAreaIncoming.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                textAreaIncomingHyperlinkUpdate(evt);
            }
        });
        scrollPaneIncoming.setViewportView(textAreaIncoming);

        getContentPane().add(scrollPaneIncoming);
        scrollPaneIncoming.setBounds(20, 20, 460, 210);

        scrollPaneOutgoing.setBorder(null);
        scrollPaneOutgoing.setOpaque(false);

        textAreaOutgoing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textAreaOutgoing.setContentType("text/html"); // NOI18N
        textAreaOutgoing.setCaretColor(new java.awt.Color(255, 255, 255));
        textAreaOutgoing.setOpaque(false);
        textAreaOutgoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textAreaOutgoingMouseReleased(evt);
            }
        });
        textAreaOutgoing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaOutgoingKeyPressed(evt);
            }
        });
        scrollPaneOutgoing.setViewportView(textAreaOutgoing);

        getContentPane().add(scrollPaneOutgoing);
        scrollPaneOutgoing.setBounds(20, 330, 270, 150);

        incomingBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/opacity77.png"))); // NOI18N
        getContentPane().add(incomingBg);
        incomingBg.setBounds(20, 20, 460, 210);

        outgoingBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/opacity77.png"))); // NOI18N
        getContentPane().add(outgoingBg);
        outgoingBg.setBounds(20, 330, 270, 150);

        tableEmojis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tableEmojis.setForeground(new java.awt.Color(255, 255, 255));
        tableEmojis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableEmojis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableEmojis.setOpaque(false);
        tableEmojis.setRowHeight(30);
        tableEmojis.setRowSelectionAllowed(false);
        tableEmojis.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tableEmojis.setShowHorizontalLines(false);
        tableEmojis.setShowVerticalLines(false);
        tableEmojis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableEmojisMouseReleased(evt);
            }
        });
        getContentPane().add(tableEmojis);
        tableEmojis.setBounds(300, 330, 170, 150);

        labelNextEmojiPage.setBackground(new java.awt.Color(51, 51, 51));
        labelNextEmojiPage.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        labelNextEmojiPage.setForeground(new java.awt.Color(255, 255, 255));
        labelNextEmojiPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNextEmojiPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/next.png"))); // NOI18N
        labelNextEmojiPage.setToolTipText("");
        labelNextEmojiPage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelNextEmojiPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelNextEmojiPage.setOpaque(true);
        labelNextEmojiPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelNextEmojiPageMouseReleased(evt);
            }
        });
        getContentPane().add(labelNextEmojiPage);
        labelNextEmojiPage.setBounds(390, 490, 30, 25);

        labelPrevEmojiPage.setBackground(new java.awt.Color(51, 51, 51));
        labelPrevEmojiPage.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        labelPrevEmojiPage.setForeground(new java.awt.Color(255, 255, 255));
        labelPrevEmojiPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrevEmojiPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/prev.png"))); // NOI18N
        labelPrevEmojiPage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelPrevEmojiPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPrevEmojiPage.setOpaque(true);
        labelPrevEmojiPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelPrevEmojiPageMouseReleased(evt);
            }
        });
        getContentPane().add(labelPrevEmojiPage);
        labelPrevEmojiPage.setBounds(350, 490, 30, 25);

        labelSend.setBackground(new java.awt.Color(51, 51, 51));
        labelSend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSend.setForeground(new java.awt.Color(255, 255, 255));
        labelSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSend.setText("ارسال");
        labelSend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSend.setOpaque(true);
        labelSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelSendMousePressed(evt);
            }
        });
        getContentPane().add(labelSend);
        labelSend.setBounds(20, 490, 130, 30);

        labelClear.setBackground(new java.awt.Color(51, 51, 51));
        labelClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelClear.setForeground(new java.awt.Color(255, 255, 255));
        labelClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClear.setText("پاک کردن");
        labelClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelClear.setOpaque(true);
        labelClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelClearMouseReleased(evt);
            }
        });
        getContentPane().add(labelClear);
        labelClear.setBounds(160, 490, 130, 30);

        labelStatusLabl.setForeground(new java.awt.Color(255, 255, 255));
        labelStatusLabl.setText("Status:");
        getContentPane().add(labelStatusLabl);
        labelStatusLabl.setBounds(20, 560, 150, 40);

        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Offline");
        getContentPane().add(labelStatus);
        labelStatus.setBounds(170, 560, 300, 40);

        backgroundOfLabels.setBackground(new java.awt.Color(51, 51, 51));
        backgroundOfLabels.setOpaque(true);
        getContentPane().add(backgroundOfLabels);
        backgroundOfLabels.setBounds(0, 560, 500, 40);

        labelFrameBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bg/batman.jpg"))); // NOI18N
        labelFrameBg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(labelFrameBg);
        labelFrameBg.setBounds(0, 0, 500, 600);

        menuFile.setText("گزینه ها");
        menuFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menuFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuFile.setMargin(new java.awt.Insets(0, 10, 0, 0));
        menuFile.setPreferredSize(new java.awt.Dimension(70, 23));
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuChangeBg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuChangeBg.setText("تغییر پس زمینه");
        menuChangeBg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuChangeBgMouseReleased(evt);
            }
        });
        menuFile.add(menuChangeBg);

        menuShowHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuShowHistory.setText("نمایش تاریخچه");
        menuShowHistory.setToolTipText("");
        menuShowHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShowHistoryActionPerformed(evt);
            }
        });
        menuFile.add(menuShowHistory);
        menuFile.add(menuSeparator1);

        menuRemoteShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuRemoteShutdown.setText("خاموش کردن از راه دور");
        menuRemoteShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoteShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuRemoteShutdown);

        menuAbortRemoteShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbortRemoteShutdown.setText("توقف خاموشی آن کامپیوتر");
        menuAbortRemoteShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbortRemoteShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuAbortRemoteShutdown);

        menuAbortLocalShutdown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbortLocalShutdown.setText("توقف خاموشی این کامپیوتر");
        menuAbortLocalShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbortLocalShutdownActionPerformed(evt);
            }
        });
        menuFile.add(menuAbortLocalShutdown);

        menuWakeOnLan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuWakeOnLan.setText("بیدار کردن");
        menuWakeOnLan.setEnabled(false);
        menuWakeOnLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWakeOnLanActionPerformed(evt);
            }
        });
        menuFile.add(menuWakeOnLan);
        menuFile.add(menuSeparator2);

        menuAbout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuAbout.setText("درباره");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuFile.add(menuAbout);

        menuExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuExit.setText("خروج");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		hideWindow();
    }//GEN-LAST:event_formWindowClosing

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        
    }//GEN-LAST:event_menuFileActionPerformed

    private void tableEmojisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmojisMouseReleased

        int row = tableEmojis.getSelectedRow();
        int col = tableEmojis.getSelectedColumn();
         
        //replace the emoticon image with the larger image. we also add the width=50 and height=50 for better display
        String img = (String) tableEmojis.getValueAt(row, col);
		img = img.replaceAll("<html>(.*)emoticons(.*\\.gif')\\s(\\/>)<\\/html>", "$1emoticons_large$2  $3");
        
        
        //true = append
        updateOutgoingText(img, true);
        textAreaOutgoing.requestFocus();
    
    }//GEN-LAST:event_tableEmojisMouseReleased

    private void textAreaIncomingHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_textAreaIncomingHyperlinkUpdate
        //triggered when we click on a link
        if(evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED){
            try{
                String path = evt.getURL().toString();
                
                //open if it was a file
                if(path.contains("file://")){
                    path = path.substring(7);
                    Desktop.getDesktop().open(new File(path));
                }
                //browse if it was a URL
                else
                    Desktop.getDesktop().browse(evt.getURL().toURI());
                
            }catch(IOException e){
                message(Helper.getInstance().getStr("url_open_fail") + e.getMessage());
            }catch(URISyntaxException e){
                message(Helper.getInstance().getStr("bad_url") + e.getMessage());
            }
        }
		
    }//GEN-LAST:event_textAreaIncomingHyperlinkUpdate

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed

        exit();
    }//GEN-LAST:event_menuExitActionPerformed

    private void panelPopupNormalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPopupNormalMouseReleased
		popopClicked();
    }//GEN-LAST:event_panelPopupNormalMouseReleased

    private void labelClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMouseReleased

        defaultOutgoingText();
    }//GEN-LAST:event_labelClearMouseReleased

    private void textAreaOutgoingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaOutgoingMouseReleased
        //show the right-click menu
        if(evt.getButton() == MouseEvent.BUTTON3){
            menuRightClick.show(textAreaOutgoing, evt.getX(), evt.getY());
        } 
    }//GEN-LAST:event_textAreaOutgoingMouseReleased

    private void dialogHistoryWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogHistoryWindowOpened
        //is run everytime history dialog opens
        
        //store incoming text
        textAreaIncomingContentBeforeHistory = incomingTextAll;
        
        historyPagination = new HistoryTablePagination(
                tableHistory,
                "history.sqlite",
                "SELECT date,text FROM chat_sessions ORDER BY date DESC"
        );

        try{
            historyPagination.nextPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            
        }catch(SQLException e){
            message(Helper.getInstance().getStr("history_fail") + e.getMessage());
        }

    }//GEN-LAST:event_dialogHistoryWindowOpened

    private void menuShowHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShowHistoryActionPerformed
        //show history dialog
        dialogHistory.setLocationRelativeTo(null);
        dialogHistory.setVisible(true);
    }//GEN-LAST:event_menuShowHistoryActionPerformed

    private void tableHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHistoryMouseReleased
        //put selected history item in textAreaIncoming
		//TODO: do
		message("unsupported");
//        int row = tableHistory.getSelectedRow();
//        String text = tableHistory.getModel().getValueAt(row, 1).toString();
//        //if we do updateIncomingText(text) then text will be regexed again. But it is already parsed and saved.
//        incomingTextAll = text;
//        updateIncomingText("<br>", false);
        
    }//GEN-LAST:event_tableHistoryMouseReleased

    private void dialogHistoryWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogHistoryWindowClosed
    }//GEN-LAST:event_dialogHistoryWindowClosed

    private void dialogHistoryWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogHistoryWindowClosing
        //restore the incoming text
		//TODO: do
		message("unsupported");
		
//        incomingTextAll = "";
//        updateIncomingText(textAreaIncomingContentBeforeHistory, false);
    }//GEN-LAST:event_dialogHistoryWindowClosing

    private void buttonNextHistoryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextHistoryPageActionPerformed
        
        try{
            historyPagination.nextPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            buttonPrevHistoryPage.setEnabled(historyPagination.hasPrev());
        }catch(SQLException e){
            message(Helper.getInstance().getStr("history_fail") + e.getMessage());
        }
    }//GEN-LAST:event_buttonNextHistoryPageActionPerformed

    private void buttonPrevHistoryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevHistoryPageActionPerformed

        try{
            historyPagination.prevPage();
            buttonNextHistoryPage.setEnabled(historyPagination.hasNext());
            buttonPrevHistoryPage.setEnabled(historyPagination.hasPrev());
        }catch(SQLException e){
            message(Helper.getInstance().getStr("history_fail") + e.getMessage());
        }
    }//GEN-LAST:event_buttonPrevHistoryPageActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(null, Helper.getInstance().getStr("license"), Helper.getInstance().getStr("about"), JOptionPane.PLAIN_MESSAGE, null);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuRemoteShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoteShutdownActionPerformed

		int answer = JOptionPane.showConfirmDialog(null, Helper.getInstance().getStr("remote_shutdown_message"), Helper.getInstance().getStr("remote_shutdown_title"), JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            ChatmanMessage message = new ChatmanMessage(ChatmanMessage.TYPE_SHUTDOWN, "", username);
			chatman.send(message);
        }
    }//GEN-LAST:event_menuRemoteShutdownActionPerformed

    private void menuWakeOnLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWakeOnLanActionPerformed
        
		throw new UnsupportedOperationException("not supported yet");
		/*
		try{
			Helper.getInstance().sendWakeOnLan("remote_ip");
			
		}catch(IOException e){
			message(Helper.getInstance().getStr("wakeonlan_fail"));
		}
		*/
    }//GEN-LAST:event_menuWakeOnLanActionPerformed

    private void labelNextEmojiPageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNextEmojiPageMouseReleased
        
		nextEmojiPage();
    }//GEN-LAST:event_labelNextEmojiPageMouseReleased

    private void labelPrevEmojiPageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevEmojiPageMouseReleased
        
		prevEmojiPage();
    }//GEN-LAST:event_labelPrevEmojiPageMouseReleased

    private void menuAbortLocalShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbortLocalShutdownActionPerformed
        
		try{
			Helper.getInstance().abortLocalShutdown();
		}catch(IOException e){
			message("couldn't stop the shutdown :(");
		}
    }//GEN-LAST:event_menuAbortLocalShutdownActionPerformed

    private void menuChangeBgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuChangeBgMouseReleased
        
		
		boolean isLeftClick = SwingUtilities.isLeftMouseButton(evt);
		
		if(isLeftClick){
			Background.getInstance().next();
		}
		else{
			Background.getInstance().prev();
		}
		
        setBackground(Background.getInstance().getCurrentURL());

        if(chatman != null)
            updateUserName();
       
        //doClick() so user doesn't have to open menu over and over again for changing bg
        menuFile.doClick();
		
    }//GEN-LAST:event_menuChangeBgMouseReleased

    private void labelSendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSendMousePressed
		send();
    }//GEN-LAST:event_labelSendMousePressed

    private void textAreaOutgoingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaOutgoingKeyPressed
		if (evt.getKeyChar() == '\n'){ 
			evt.consume();
            send();
        }
    }//GEN-LAST:event_textAreaOutgoingKeyPressed

    private void menuAbortRemoteShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbortRemoteShutdownActionPerformed
		int answer = JOptionPane.showConfirmDialog(null, Helper.getInstance().getStr("abort_remote_shutdown_message"), Helper.getInstance().getStr("abort_remote_shutdown_title"), JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            ChatmanMessage message = new ChatmanMessage(ChatmanMessage.TYPE_ABORT_SHUTDOWN, "", username);
			chatman.send(message);
        }
    }//GEN-LAST:event_menuAbortRemoteShutdownActionPerformed

    private void labelBatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBatMouseReleased
        popopClicked();
    }//GEN-LAST:event_labelBatMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


		/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChatFrame frame = ChatFrame.getInstance();
                frame.myInits();
                frame.startChatman();
            }
        });
    }
     

    public void myInits(){
		
		createTrayIcon();
        
        //Locale
		Helper.getInstance().setLocale(ChatmanConfig.getInstance().getLocale());

        //setup GUI elements texts accordig to locale
        setupGUITexts();
		
		//set popup type
		newMessagePopup = dialogPopupBat;
		newMessagePopup.setMode(PopupDialog.MODE_BAT);
		
        //TextArea Dorp
        //We read the whole file as text and then base64_encode it which causes a LOT of memory
        //to be consumed. But i'm lazy, so it's ok.
        textAreaOutgoing.setDropTarget(new DropTarget() {
            public synchronized void drop(DropTargetDropEvent evt) {
				//TODO: har jaii ke goftam "not supported" ro doros konam
                try {
                    //clear any text
                    defaultOutgoingText();
                    
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) 
							evt.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    for (File file : droppedFiles) {
                        textAreaOutgoing.setText(file.getAbsolutePath());
                        //check file size
						//TODO: promot instead of forbidding
                        int max = Integer.valueOf(ChatmanConfig.getInstance().get("max-file-size"));
                        if(file.length()> max*1000*1000){
                            message(Helper.getInstance().getStr("max_file_size") + max + "MB");
                            continue;
                        }
                        //send the file
						String filePath = file.getAbsolutePath();
						String fileName = file.getName();
						ChatmanMessage fileMessageRemote = new ChatmanMessage(ChatmanMessage.TYPE_FILE, filePath, fileName);
						boolean sent = chatman.send(fileMessageRemote);
                        //show file sent message and clear textAreaOutgoing
						if(sent){
							String content = fileName;
							String sender = Helper.getInstance().getStr("file_sent");
							ChatmanMessage fileMessageLocal = new ChatmanMessage(ChatmanMessage.TYPE_TEXT, content, sender);
							updateIncomingText(fileMessageLocal);
						}
						defaultOutgoingText();
                    }
                } catch (Exception ex) {
                    message(Helper.getInstance().getStr("open_file_fail"));
                }
            }
        });
        

        //TextArea right click
        
        //create a paste action because the default is problematic
        Action paste = new AbstractAction(Helper.getInstance().getStr("paste")) {
            @Override
            public void actionPerformed(ActionEvent e) {
                textAreaOutgoing.paste();
                String s = textAreaOutgoing.getText();
                //clear html tags and new lines
                s = s.replaceAll("<[\\/\\w]*>", "").replace("\n", "").trim();
                updateOutgoingText(s,true);
            }
        }; 
        
        //setup copy and cut
        Action copyAction = textAreaOutgoing.getActionMap().get(DefaultEditorKit.copyAction);
        copyAction.putValue("Name", Helper.getInstance().getStr("copy"));
        Action cutAction = textAreaOutgoing.getActionMap().get(DefaultEditorKit.cutAction);
        cutAction.putValue("Name", Helper.getInstance().getStr("cut"));
        
        menuRightClick.add (paste); 
        menuRightClick.add (copyAction);
        menuRightClick.add (cutAction);

        
        //TextArea cursor
        ((HTMLEditorKit)textAreaOutgoing.getEditorKit()).setDefaultCursor(new Cursor(Cursor.TEXT_CURSOR));
        
        
        //TextArea focus
        textAreaOutgoing.requestFocus();
        
        
        //Table BG
        tableEmojis.setBackground(new Color(50,50,50,170));  

        
        //Populate Table
        //!!!IMPORTANT: only words in emoticons name 
        //!!!IMPORTANT: emoticons should have .gif extention and be stored in /resources/emoticons folder
        //!!!IMPORTANT: any change made here, or to emoticons names,format,folder,etc. should be also applied to regular expression accross the code
        emoticonsArray = new String[][][]{
			{
				{"hi", "smoke", "xd", "amazing", "victory"},
				{"bleed", "desperate", "spiral", "shake", "shooting"},
				{"calmdownwide", "killwide", "getout", "wallbangwide", "extraordinary"},
				{"yes", "grumpyno", "grumpy", "dog", "epicface"},
				{"snail", "wifi", "reset", "power", "question"}
			},
			{
				{"badluck", "ballerina", "boring", "dancing", "dizzy"},
				{"dunno", "exorcist", "flying", "happiness", "dancingg"},
				{"happyy", "help", "killme", "killmyself", "looser"},
				{"magic", "dreaming", "nah", "nono", "patpat"},
				{"poking", "scratching", "sleeping", "smooth", "stars"}
			},
			{
				{"steal", "taichi", "teehee", "what", "yeah"},
				{"yesss", "yipee", "dancingg", "bat", "na"},
				{"na", "na", "na", "na", "na"},
				{"na", "na", "na", "na", "na"},
				{"na", "na", "na", "na", "na"}
			}
        };
		nextEmojiPage();
		
       
        //Frame BG
        setBackground(Background.getInstance().getCurrentURL());
       
        //Empty HTML Texts
        defaultTextAreaHtml = new String[2];
        defaultTextAreaHtml[0] = "<html><head><style type=\"text/css\">#text { color: white; font-family: Tahoma; font-size: 12px; }</style></head><body><div id=\"text\">";
        defaultTextAreaHtml[1] = "</div></body></html>";
        defaultOutgoingText();
        defaultIncomingText();        
        
        
        //Make ScrollPanes invisible
        scrollPaneOutgoing.setOpaque(false);
        scrollPaneOutgoing.getViewport().setOpaque(false);
        scrollPaneIncoming.setOpaque(false);
        scrollPaneIncoming.getViewport().setOpaque(false);
		
		
        //Icons
        //main frame
        java.net.URL url = getClass().getResource("/resources/icon.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        this.setIconImage(img);
        
        //history dialog
        url = getClass().getResource("/resources/history.png");
        img = kit.createImage(url);
        dialogHistory.setIconImage(img);
        

        //Center
        this.setLocationRelativeTo(null);
		
		//Hide wake on lan menu
		menuWakeOnLan.setVisible(false);
		
		//Iransans font for send and clear
		try{
			InputStream is = getClass().getResourceAsStream("/resources/iransans.ttf");
			Font font = Font.createFont(Font.TRUETYPE_FONT, is);
			Font iranSans = font.deriveFont(15f);
			labelSend.setFont(iranSans);
			labelClear.setFont(iranSans);
		}catch(Exception e){
			//font will revert to Tahoma
		}
		
		updateUserName();
 
    } 
    
    //start Chatman as client/server
    public void startChatman(){
		chatman = new Chatman();
		chatman.getServer().start();
    }
    

    
    //Called from myInits()
	public void createTrayIcon(){
        if (!SystemTray.isSupported()) {
			//TODO: convert to log
            message("System tray not supported");
            return;
        }
		ImageIcon ticon = new ImageIcon(getClass().getResource("/resources/trayicon.png"));
        final TrayIcon trayIcon = new TrayIcon(ticon.getImage());
		trayIcon.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				popopClicked();
			}
		});
        final SystemTray tray = SystemTray.getSystemTray();
        try {
            tray.add(trayIcon);
        } catch (AWTException e) {
			//TODO: convert to log
            message("Tray icon could not be added");
        }
	}
	
    public void setupGUITexts(){
        labelNewMessage.setText(Helper.getInstance().getStr("new_message"));
        dialogHistory.setTitle(Helper.getInstance().getStr("history"));
        buttonNextHistoryPage.setText(Helper.getInstance().getStr("next_page"));
        buttonPrevHistoryPage.setText(Helper.getInstance().getStr("prev_page"));
        labelSend.setText(Helper.getInstance().getStr("send"));
        labelClear.setText(Helper.getInstance().getStr("clear"));
        labelStatusLabl.setText(Helper.getInstance().getStr("status"));
        labelStatus.setText(Helper.getInstance().getStr("offline"));
        menuFile.setText(Helper.getInstance().getStr("options"));
        menuChangeBg.setText(Helper.getInstance().getStr("change_bg"));
        menuShowHistory.setText(Helper.getInstance().getStr("show_history"));
		menuRemoteShutdown.setText(Helper.getInstance().getStr("remote_shutdown"));
		menuAbortLocalShutdown.setText(Helper.getInstance().getStr("abort_local_shutdown"));
		menuAbortRemoteShutdown.setText(Helper.getInstance().getStr("abort_remote_shutdown"));
		menuWakeOnLan.setText(Helper.getInstance().getStr("wakeonlan"));
        menuAbout.setText(Helper.getInstance().getStr("about"));
        menuExit.setText(Helper.getInstance().getStr("exit"));
    }
	
	//populates a table with emoticons and returns the table model
	public AbstractTableModel getEmoticonTable(String[][] emoticonsArray){
		
			//make table cells uneditable
			AbstractTableModel model = new DefaultTableModel(5, 5){
				@Override
				public boolean isCellEditable(int row, int column){
					return false;
				}
			};

			//add emoticons to cells
			for(int row = 0;row<5;row++){
				for(int col = 0;col<5;col++){
					String name = emoticonsArray[row][col];
					URL url = getClass().getResource("/resources/emoticons/" + name + ".gif");
					if(url != null)
						name = url.toString();
					String h = "<html><img src='" + name + "' /></html>";
					model.setValueAt(h, row, col);
				}
			}
			
			return model;
	}
	
	//loads next set of emojis
	public void nextEmojiPage(){
		
		if(emojisIndex >= (emoticonsArray.length - 1) ){
			emojisIndex = 0;
		}
		else{
			emojisIndex++;
		}
		
		AbstractTableModel model = getEmoticonTable(emoticonsArray[emojisIndex]);
		tableEmojis.setModel(model);
		
	}
	
	//loads previous set of emojis
	public void prevEmojiPage(){
		
		if(emojisIndex <= 0){
			emojisIndex = (emoticonsArray.length -1);
		}
		else{
			emojisIndex--;
		}
		
		AbstractTableModel model = getEmoticonTable(emoticonsArray[emojisIndex]);
		tableEmojis.setModel(model);
		
	}
    
    //sends the content of textAreaOutgoing
    private void send(){
		     
        String s = getOutgoingText();
        
        //return if textarea is empty
        if(s.isEmpty())
            return;

		ChatmanMessage message = new ChatmanMessage(ChatmanMessage.TYPE_TEXT, s, username);
		boolean sent = chatman.send(message);

		if(sent){
			message.setSender("You");
			updateIncomingText(message);
			defaultOutgoingText();
		}
		
    }
    
    //parses the string that is given to it and adds it to textAreaIncoming
    //it is called both when we send a message or receive a message
	//TODO: change the name of "IncomingText" to "AllMessages" or something
    public void updateIncomingText(ChatmanMessage message, boolean bleep){
        //updates the textareaIncoming. Is run when we say something or the other guy says something
        
        //popup when first message received
        if(isHidden()){
            newMessagePopup.showPopup();
            newMessagePopup.playSound();
        }
        //bleep if we received message and was not focused
        else if(!this.isActive() && bleep){
            newMessagePopup.playSound();
        }

        if(message.getContent().isEmpty()){
            defaultIncomingText();
            return;
        }
        
		//TODO: files
        //parse file links
        //t = t.replaceAll("(file:\\/\\/([^\\.]*\\..*))", "<a style='color:#dee3e9;font-weight:bold;' href='$1'>$2</a> ");
        
		incomingTextAll += message.getDisplayableContent();
		chatman.addToUnsavedMessages(message);
		
		textAreaIncoming.setText(defaultTextAreaHtml[0] + incomingTextAll + defaultTextAreaHtml[1]);
		
		//wait 100ms in another thread and then scroll the incoming text all the way down
		//because the fucking thing just doesn't work any other way
		Runnable r = new Runnable() {
			@Override
			public void run() {
				try{
					Thread.sleep(100);
					SwingUtilities.invokeLater(new Runnable() {
						@Override
						public void run() {
							scrollDownIncomingText();
						}
					});
				}catch(Exception e){
					
				}
			}
		};
		Thread th = new Thread(r);
		th.start();
		        
    }
    
    //lazy version 
    public void updateIncomingText(ChatmanMessage message){
        updateIncomingText(message, true);
    }
    
    //clears textAreaIncoming
    public void defaultIncomingText(){
        textAreaIncoming.setText(defaultTextAreaHtml[0] + defaultTextAreaHtml[1]);
    }
	
	public void scrollDownIncomingText(){
		JScrollBar vertical = scrollPaneIncoming.getVerticalScrollBar();
		vertical.setValue( vertical.getMaximum() );
	}
    
    //is called when we want to add something to the outgoing text like emoticons, paste stuff, or disconnect message
    public void updateOutgoingText(String t, boolean append){

        if(append){
            textAreaOutgoing.setText(defaultTextAreaHtml[0] + getOutgoingText() + t + defaultTextAreaHtml[1]);
        }
        else{
            textAreaOutgoing.setText(defaultTextAreaHtml[0] + t + defaultTextAreaHtml[1]);
        }
    }
    
    //because i couldn't find a way to get the text in a clean manner, i am extracting stuff between <div></div> tags
    //which i have added for this porpuse to defaultTextAreaHtml
    public String getOutgoingText(){
        String s = textAreaOutgoing.getText();
        if(!s.contains("<div id=\"text\">"))
            return "";
        return s.substring((s.indexOf("<div id=\"text\">"))+15, (s.indexOf("</div>"))-1).trim();
    }
    
    //clears textAreaOutgoing
    public void defaultOutgoingText(){
        textAreaOutgoing.setText(defaultTextAreaHtml[0] + defaultTextAreaHtml[1]);
    }
    
    //well, sets the background
    public void setBackground(URL url){
        labelFrameBg.setIcon(new javax.swing.ImageIcon(url));
    }
    

	
    public void updateUserName(){
        //background names are like batman_1.jpg or batman.png
        String name = Background.getInstance().getCurrent().split("\\.")[0].split("_")[0];        
        name = name.substring(0, 1).toUpperCase() + name.substring(1,name.length());
		username = name;
    }
	
    //disable textAreaOutgoing and put a message in it
    public void endSession(String message){
        updateOutgoingText("<span style='font-size:20px;'>" + message + "</span>", false);
        textAreaOutgoing.setEnabled(false);
    }
	
	public void disableTextOutgoing(){
		textAreaOutgoing.setEnabled(false);
	}
	
	public void enableTextOutgoing(){
		textAreaOutgoing.setEnabled(true);
	}
    
    //gives us the hero that we don't deserve
    public Chatman getChatmanInstance(){
        return chatman;
    }
	
	public void popopClicked(){
        //close the "New Message" popup and show the application window
        newMessagePopup.hidePopup();
        //Show
        showWindow();
        //Focus
        textAreaOutgoing.requestFocus();
	}

    //sets the status label at the bottom
    public void setLabelStatus(String s){
        labelStatus.setText(s);
    }
    
    //shows a message
    public void message(String m){
        m = "<html><span style='font-size:14px;'>" + m + "</span></html>";
        JOptionPane.showMessageDialog(null, m);
    } 
    
    //the mask is for the ones you love. we stay hidden unless it's neccessary to show up
    public boolean isHidden(){
        return !this.isVisible() && !newMessagePopup.isVisible();
    }
	
	//hides the chatman windows
	public void hideWindow(){
		this.setVisible(false);
	}
	
	//shows the chatman window
	public void showWindow(){
		this.setVisible(true);
		if(!((HttpClient)chatman.getClient()).isServerFound()){
			chatman.getClient().connect();
		}
	}
	
	//TODO: calling exit after calling CommandInvokeLater() exits application immediately and that command is never invoked. so check all calls to exit and remove such cases
    //the end of chatman. that's it. no auto pilot :(
    public synchronized void exit(){
		
        chatman.saveHistory();
                
        ChatmanConfig.getInstance().save();
		      
        System.exit(0);
		
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundOfLabels;
    private javax.swing.JButton buttonNextHistoryPage;
    private javax.swing.JButton buttonPrevHistoryPage;
    private javax.swing.JDialog dialogHistory;
    private com.pouria.chatman.gui.PopupDialog dialogPopupBat;
    private com.pouria.chatman.gui.PopupDialog dialogPopupNormal;
    private javax.swing.JLabel incomingBg;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelBat;
    private javax.swing.JLabel labelClear;
    private javax.swing.JLabel labelFrameBg;
    private javax.swing.JLabel labelMessageIcon;
    private javax.swing.JLabel labelNewMessage;
    private javax.swing.JLabel labelNextEmojiPage;
    private javax.swing.JLabel labelPrevEmojiPage;
    private javax.swing.JLabel labelSend;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStatusLabl;
    private javax.swing.JMenuItem menuAbortLocalShutdown;
    private javax.swing.JMenuItem menuAbortRemoteShutdown;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuChangeBg;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuRemoteShutdown;
    private javax.swing.JPopupMenu menuRightClick;
    private javax.swing.JPopupMenu.Separator menuSeparator1;
    private javax.swing.JPopupMenu.Separator menuSeparator2;
    private javax.swing.JMenuItem menuShowHistory;
    private javax.swing.JMenuItem menuWakeOnLan;
    private javax.swing.JLabel outgoingBg;
    private javax.swing.JPanel panelPopupNormal;
    private javax.swing.JScrollPane scrollPaneHistory;
    private javax.swing.JScrollPane scrollPaneIncoming;
    private javax.swing.JScrollPane scrollPaneOutgoing;
    private javax.swing.JTable tableEmojis;
    private javax.swing.JTable tableHistory;
    private javax.swing.JEditorPane textAreaIncoming;
    private javax.swing.JEditorPane textAreaOutgoing;
    // End of variables declaration//GEN-END:variables
}
